/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.playground;

import static io.playground.RocksLoad.doReads;
import static io.playground.RocksLoad.doWrites;

import com.google.common.primitives.Longs;
import java.util.Random;
import org.rocksdb.Options;
import org.rocksdb.RocksDB;
import org.rocksdb.RocksDBException;

public class Playground1MReadsWrites {

    public static void main(String[] args) {

        RocksDB.loadLibrary();

        try (final Options options = new Options().setCreateIfMissing(true)) {
            try (final RocksDB db = RocksDB.open(options, "/tmp/rocksdb-2")) {

                    doWrites(db);

                    doReads(db);
            }

        } catch (RocksDBException e) {
            e.printStackTrace();
        }
    }
}
