/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.playground;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Playground1MReadsWritesTest {
    @Test void appHasAGreeting() {
    }
}
